config/routes.rb
Rails.application.routes.draw do
  get 'about/show'

  get 'contact/show'

  get 'sessions/new'

  root to: 'finder#index'

  resources :products, only: [:index, :show]
  resources :customers, only: [:show, :new, :create, :edit, :update]

  get 'phones' => 'finder#phones'
  get 'tablets' => 'finder#tablets'
  get 'laptops' => 'finder#laptops'

  get '/signup' => 'customers#new'
  post '/users' => 'customers#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_secure_password

  validates :name, :address, :phone, :email, :password, :postal_code, :city, presence: true
  validates :email, uniqueness: true, email_format: true

  belongs_to :province
  has_many :orders
end

app/models/design.rb
class Design < ApplicationRecord
  has_attached_file :image, styles: { medium: '300x300#', thumb: '200x200#' }, default_url: '/images/:style/no-image.png'
  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\z}

  validates :name, presence: true

  has_many :products
  has_many :devices, through: :products

  attr_accessor :remove_image

  def delete_image
    @remove_image || false
  end

  before_validation { image.clear if remove_image == '1' }
end

app/models/device.rb
class Device < ApplicationRecord
  validates :name, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  has_many :models
  has_many :products
  has_many :designs, through: :products
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :products
  belongs_to :order
end

app/models/model.rb
class Model < ApplicationRecord
  validates :name, :brand, presence: true
  validates :name, uniqueness: true

  belongs_to :device
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items
  has_many :products, through: :line_items
  belongs_to :customer
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :design
  belongs_to :device
  has_many :line_items
  has_many :orders, through: :line_items

  scope :phones, -> { joins(:device).where('name = ?', 'Phone') }
  scope :tablets, -> { joins(:device).where('name = ?', 'Tablet') }
  scope :laptops, -> { joins(:device).where('name = ?', 'Laptop') }
end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, presence: true
  validates :gst_rate, :pst_rate, :hst_rate, numericality: { allow_nil: true }

  has_many :customers
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def new
    @customer = Customer.new
    @provinces = Province.order(:name).all
  end

  def edit
    @provinces = Province.order(:name).all
  end

  def create
    @customer = Customer.new(customer_params)
    @provinces = Province.all

    if @customer.save
      session[:customer_id] = @customer.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  def update
    @provinces = Province.all

    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def customer_params
    params.require(:customer).permit(:name, :address, :city, :postal_code,
                                     :phone, :email, :password,
                                     :password_confirmation, :password_digest,
                                     :province_id)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group row">
    <%= f.label :name, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :address, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :city, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :province_id, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
       <%= f.collection_select :province_id, @provinces, :id, :name, {include_blank: false}, {class: 'form-control'} %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :postal_code, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
       <%= f.text_field :postal_code, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :phone, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
      <%= f.text_field :phone, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :email, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :password, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= f.label :password_confirmation, 'Confirm Password', class: "col-sm-2 col-form-label" %>
    <div class="col-sm-5">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>

  <%= f.submit 'Submit', class: "btn" %>

<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>Province:</strong>
  <%= @customer.province.name %>
</p>

<p>
  <strong>Postal Code:</strong>
  <%= @customer.postal_code %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %>