config/routes.rb
Rails.application.routes.draw do
  get 'about/show'

  get 'contact/show'

  get 'sessions/new'

  root to: 'finder#index'

  resources :products, only: [:index, :show]
  resources :customers, only: [:show, :new, :create, :edit, :update]

  get 'phones' => 'finder#phones'
  get 'tablets' => 'finder#tablets'
  get 'laptops' => 'finder#laptops'

  get '/signup' => 'customers#new'
  post '/users' => 'customers#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_secure_password

  validates :name, :address, :phone, :email, :password, :postal_code, :city, presence: true
  validates :email, uniqueness: true, email_format: true

  belongs_to :province
  has_many :orders
end

app/models/design.rb
class Design < ApplicationRecord
  has_attached_file :image, styles: { medium: '300x300#', thumb: '200x200#' }, default_url: '/images/:style/no-image.png'
  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\z}

  validates :name, presence: true

  has_many :products
  has_many :devices, through: :products

  attr_accessor :remove_image

  def delete_image
    @remove_image || false
  end

  before_validation { image.clear if remove_image == '1' }
end

app/models/device.rb
class Device < ApplicationRecord
  validates :name, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  has_many :models
  has_many :products
  has_many :designs, through: :products
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :products
  belongs_to :order
end

app/models/model.rb
class Model < ApplicationRecord
  validates :name, :brand, presence: true
  validates :name, uniqueness: true

  belongs_to :device
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items
  has_many :products, through: :line_items
  belongs_to :customer
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :design
  belongs_to :device
  has_many :line_items
  has_many :orders, through: :line_items

  scope :phones, -> { joins(:device).where('name = ?', 'Phone') }
  scope :tablets, -> { joins(:device).where('name = ?', 'Tablet') }
  scope :laptops, -> { joins(:device).where('name = ?', 'Laptop') }
end

app/models/province.rb
class Province < ApplicationRecord
  validates :name, presence: true
  validates :gst_rate, :pst_rate, :hst_rate, numericality: { allow_nil: true }

  has_many :customers
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saiyabit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_customer %>
      Signed in as <%= current_customer.name %> | <%= link_to "Logout", '/logout' %>
    <% else %>
      <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
    <% end %>
    | <%= link_to 'Admin', new_admin_user_session_path %>
    <%= render 'shared/menu' %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <a class="navbar-brand" href="#">Saiyabit</a>
  <ul class="nav navbar-nav">
    <li class="nav-item"><%= link_to 'Home', root_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to 'Phone Cases', phones_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to 'Tablet Cases', tablets_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to 'Laptop Cases', laptops_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to 'Contact', contact_show_path, class: "nav-link" %></li>
    <li class="nav-item"><%= link_to 'About', about_show_path, class: "nav-link" %></li>
  </ul>
  <%= form_tag(products_path, :method => "get", id: "search-form", class: "form-inline float-xs-right") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search...", class: "form-control" %>
    <%= select_tag :device_id, options_from_collection_for_select(Device.all, :id, :name, params[:device_id]), include_blank: true, class: "form-control" %>
    <%= submit_tag "Search", class: "btn" %>
  <% end %>
</nav>